class Config():
    controllerip = '10.190.88.254'
    project_id = '8a935f01bcef4035912cae8cd604228d'
    user_id = '35be9b6b4b03433fa2aeba6df8c0a701'
    password = 'admin252'
    security_groups = 'open'
    availability_zone = 'nova'
    diskConfig = 'AUTO'
    network_name = 'demo-net'
    key_name = 'cherrypick'
    plugin_name = 'sandbox'
    hadoop_version = '2.7.1'
    floating_ip_pool_id = ''
    # master_nodegroup_template_name = 'm1-xlarge-master'
    # slave_nodegroup_template_name = 'm1-xlarge-slave'
    # cluster_template_name = 'm1-xlarge-4'
    # cluster_name = 'lb-m1-xlarge-4'
    # master_node_count = 1
    # slave_node_count = 3