class Config():
    controllerip = '10.141.105.23'
    project_id = 'fbf563d4c77b47cbbf826684da3d706e'
    user_id = 'fb9fc79dcebd4eb3be07c3f36d168874'
    password = 'admin'
    security_groups = 'open'
    availability_zone = 'nova'
    diskConfig = 'AUTO'
    network_name = 'demo-net'
    key_name = 'cherrypick'
    plugin_name = 'sandbox'
    hadoop_version = '2.7.1'
    floating_ip_pool_id = ''
    # master_nodegroup_template_name = 'm1-xlarge-master'
    # slave_nodegroup_template_name = 'm1-xlarge-slave'
    # cluster_template_name = 'm1-xlarge-4'
    # cluster_name = 'lb-m1-xlarge-4'
    # master_node_count = 1
    # slave_node_count = 3